# Generated by Django 3.2.10 on 2022-01-03 07:51
""" Migration definition because I renamed code field in Room model """
import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.generate_unique_code,
                                   max_length=8, unique=True),
        ),
    ]
