# Generated by Django 3.2.10 on 2022-01-03 09:03
""" Migration definition because I renamed access_token field """
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytokens',
            old_name='access',
            new_name='access_token',
        ),
    ]
