# Generated by Django 3.2.10 on 2022-01-04 07:49
""" Migration definition because I renamed song_id field in Vote model """
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='song',
            new_name='song_id',
        ),
    ]
